// src/components/ui/button.tsx
type ButtonProps = {
  label: string
  onClick?: () => void
  type?: "button" | "submit" | "reset"
  variant?: "primary" | "secondary" | "danger" | "ghost" | "outline"
  className?: string
  icon?: React.ReactNode
}

export default function Button({
  label,
  onClick,
  type = "button",
  variant = "primary",
  className = "",
  icon,
}: ButtonProps) {
  const baseStyles =
    "inline-flex items-center justify-center px-4 py-2 rounded-xl text-sm font-medium transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary/20 disabled:opacity-50 disabled:cursor-not-allowed gap-2"

  const variants: Record<string, string> = {
    primary: "bg-primary text-white hover:bg-primary/90 shadow-sm",
    secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
    outline: "bg-transparent border border-border text-foreground hover:bg-secondary/50",
    danger: "bg-red-500 text-white hover:bg-red-600 shadow-sm",
    ghost: "bg-transparent text-muted-foreground hover:text-foreground hover:bg-secondary/50",
  }

  return (
    <button
      type={type}
      onClick={onClick}
      className={`${baseStyles} ${variants[variant]} ${className}`}
    >
      {icon}
      {label}
    </button>
  )
}

// src/app/shared/components/ui/button/button.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';

type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'danger' | 'ghost';

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './button.component.html',
  styleUrl: './button.component.css',
})
export class ButtonComponent {
  @Input() label!: string;
  @Input() type: 'button' | 'submit' | 'reset' = 'button';
  @Input() variant: ButtonVariant = 'primary';
  @Input() className: string = '';
  @Input() icon?: string;
  @Output() onClick = new EventEmitter<void>();

  baseStyles =
    'inline-flex items-center justify-center px-4 py-2 rounded-xl text-sm font-medium transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary/20 disabled:opacity-50 disabled:cursor-not-allowed gap-2';

  variants: Record<ButtonVariant, string> = {
    primary: 'bg-primary text-white hover:bg-primary/90 shadow-sm',
    secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
    outline:
      'bg-transparent border border-border text-foreground hover:bg-secondary/50',
    danger: 'bg-red-500 text-white hover:bg-red-600 shadow-sm',
    ghost:
      'bg-transparent text-muted-foreground hover:text-foreground hover:bg-secondary/50',
  };

  handleClick() {
    this.onClick.emit();
  }
}

<button
  [type]="type"
  (click)="handleClick()"
  [ngClass]="[baseStyles, variants[variant], className]"
>
  <span *ngIf="icon" class="inline-flex" [innerHTML]="icon"></span>
  {{ label }}
</button>
