// src/components/ui/input.tsx
type InputProps = {
  label: string
  type?: string
  value: string
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void
  placeholder?: string
  required?: boolean
  className?: string
  icon?: React.ReactNode
  dark?: boolean
}

export default function Input({
  label,
  type = "text",
  value,
  onChange,
  placeholder,
  required = false,
  className = "",
  icon,
  dark = false,
}: InputProps) {
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (typeof onChange === 'function') {
      onChange(e)
    }
  }

  return (
    <div className={`flex flex-col gap-1.5 ${className}`}>
      <label className="text-sm font-medium text-muted-foreground px-1">
        {label}
      </label>
      <div className="relative group">
        {icon && (
          <div className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground group-focus-within:text-primary transition-colors duration-200">
            {icon}
          </div>
        )}
        <input
          type={type}
          value={value}
          onChange={handleChange}
          placeholder={placeholder}
          required={required}
          className={`w-full h-10 ${icon ? 'pl-10' : 'px-4'
            } py-2 rounded-xl text-sm font-medium transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary/20
            ${dark
              ? 'bg-gray-800 border-gray-700 text-white placeholder-gray-400'
              : 'bg-secondary border-border text-foreground placeholder-muted-foreground/60'
            }`}
        />
      </div>
    </div>
  )
}

// src/app/shared/components/ui/input/input.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-input',
  imports: [CommonModule],
  templateUrl: './input.component.html',
  styleUrl: './input.component.css',
})
export class InputComponent {
  @Input() label!: string;
  @Input() type: string = 'text';
  @Input() value: string = '';
  @Input() placeholder?: string;
  @Input() required: boolean = false;
  @Input() className: string = '';
  @Input() icon?: string; // HTML or class
  @Input() dark: boolean = false;
  @Output() valueChange = new EventEmitter<string>();

  onInputChange(e: Event) {
    const target = e.target as HTMLInputElement;
    this.valueChange.emit(target.value);
  }
}

<div [ngClass]="'flex flex-col gap-1.5 ' + className">
  <label class="text-sm font-medium text-muted-foreground px-1">{{ label }}</label>
  <div class="relative group">
    <div *ngIf="icon" class="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground group-focus-within:text-primary transition-colors duration-200" [innerHTML]="icon"></div>
    <input
      [type]="type"
      [value]="value"
      (input)="onInputChange($event)"
      [placeholder]="placeholder"
      [required]="required"
      [ngClass]="dark
        ? 'w-full h-10 pl-10 py-2 rounded-xl text-sm font-medium bg-gray-800 border-gray-700 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-primary/20'
        : 'w-full h-10 pl-10 py-2 rounded-xl text-sm font-medium bg-secondary border-border text-foreground placeholder-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-primary/20'"
    />
  </div>
</div>
