// src/components/ui/Input.tsx
type InputProps = {
  label: string
  type?: string
  value: string
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void
  placeholder?: string
  required?: boolean
  dark?: boolean
}

export default function Input({
  label,
  type = "text",
  value,
  onChange,
  placeholder,
  required = false,
  dark = false,
}: InputProps) {
  const base =
    "px-3 py-2 rounded-md text-sm focus:outline-none focus:ring-2"

  const lightStyles =
    "border border-gray-300 bg-white text-gray-900 focus:ring-primary"

  const darkStyles =
    "border border-gray-700 bg-gray-800 text-gray-100 placeholder-gray-400 focus:ring-primary"

  return (
    <div className="flex flex-col gap-1">
      <label className="text-sm font-medium text-gray-400">
        {label}
      </label>
      <input
        type={type}
        value={value}
        onChange={onChange}
        placeholder={placeholder}
        required={required}
        className={`${base} ${dark ? darkStyles : lightStyles}`}
      />
    </div>
  )
}

// src/app/shared/components/ui/input/input.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-input',
  imports: [CommonModule],
  templateUrl: './input.component.html',
  styleUrl: './input.component.css',
})
export class InputComponent {
  @Input() label!: string;
  @Input() type: string = 'text';
  @Input() value: string = '';
  @Input() placeholder?: string;
  @Input() required: boolean = false;
  @Input() className: string = '';
  @Input() icon?: string; // HTML or class
  @Input() dark: boolean = false;
  @Output() valueChange = new EventEmitter<string>();

  onInputChange(e: Event) {
    const target = e.target as HTMLInputElement;
    this.valueChange.emit(target.value);
  }
}

<div [ngClass]="'flex flex-col gap-1.5 ' + className">
  <label class="text-sm font-medium text-muted-foreground px-1">{{ label }}</label>
  <div class="relative group">
    <div *ngIf="icon" class="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground group-focus-within:text-primary transition-colors duration-200" [innerHTML]="icon"></div>
    <input
      [type]="type"
      [value]="value"
      (input)="onInputChange($event)"
      [placeholder]="placeholder"
      [required]="required"
      [ngClass]="dark
        ? 'w-full h-10 pl-10 py-2 rounded-xl text-sm font-medium bg-gray-800 border-gray-700 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-primary/20'
        : 'w-full h-10 pl-10 py-2 rounded-xl text-sm font-medium bg-secondary border-border text-foreground placeholder-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-primary/20'"
    />
  </div>
</div>
