// src/components/ui/table.tsx
type TableProps = {
    headers: string[]
    rows: any[]
    renderRow: (row: any, index: number) => React.ReactNode
    className?: string
}

export default function Table({
    headers,
    rows,
    renderRow,
    className = "",
}: TableProps) {
    return (
        <div className={`overflow-x-auto ${className}`}>
            <table className="w-full text-left border-collapse">
                <thead>
                    <tr className="border-b border-border">
                        {headers.map((header) => (
                            <th
                                key={header}
                                className="pb-4 pt-0 px-4 text-xs font-semibold text-muted-foreground uppercase tracking-wider"
                            >
                                {header}
                            </th>
                        ))}
                    </tr>
                </thead>
                <tbody>
                    {rows.map((row, index) => (
                        <tr
                            key={index}
                            className="border-b border-border/50 hover:bg-secondary/30 transition-colors duration-150 last:border-0"
                        >
                            {renderRow(row, index)}
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    )
}

// src/app/shared/components/ui/table/table.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, TemplateRef, ContentChild } from '@angular/core';

@Component({
  selector: 'app-table',
  imports: [CommonModule],
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.css'],
})
export class TableComponent {
  @Input() headers: string[] = [];
  @Input() rows: any[] = [];
  @Input() className: string = '';

  @ContentChild('rowTemplate') rowTemplate!: TemplateRef<any>;

  renderRow(row: any, index: number): TemplateRef<any> | null {
    return this.rowTemplate;
  }
}

<div [ngClass]="'overflow-x-auto ' + className">
  <table class="w-full text-left border-collapse">
    <thead>
      <tr class="border-b border-border">
        <th
          *ngFor="let header of headers"
          class="pb-4 pt-0 px-4 text-xs font-semibold text-muted-foreground uppercase tracking-wider"
        >
          {{ header }}
        </th>
      </tr>
    </thead>
    <tbody>
      <tr
        *ngFor="let row of rows; let i = index"
        class="border-b border-border/50 hover:bg-secondary/30 transition-colors duration-150 last:border-0"
      >
        <ng-container
          *ngIf="rowTemplate"
          [ngTemplateOutlet]="rowTemplate"
          [ngTemplateOutletContext]="{ $implicit: row, index: i }"
        ></ng-container>
      </tr>
    </tbody>
  </table>
</div>
