// src/app/shared/components/ui/card/card.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-card',
  imports: [CommonModule],
  templateUrl: './card.component.html',
  styleUrl: './card.component.css',
})
export class CardComponent {
  @Input() title?: string;
  @Input() description?: string;
  @Input() headerAction?: string; // or HTML
  @Input() className: string = '';
}

<div [ngClass]="'apple-card p-6 ' + className">
  <div
    *ngIf="title || description || headerAction"
    class="flex items-center justify-between mb-6"
  >
    <div>
      <h3
        *ngIf="title"
        class="text-lg font-semibold tracking-tight text-foreground"
      >
        {{ title }}
      </h3>
      <p *ngIf="description" class="text-sm text-muted-foreground">
        {{ description }}
      </p>
    </div>
    <div *ngIf="headerAction" [innerHTML]="headerAction"></div>
  </div>
  <ng-content></ng-content>
</div>

// src/components/ui/card.tsx
type CardProps = {
    children: React.ReactNode
    title?: string
    description?: string
    className?: string
    headerAction?: React.ReactNode
}

export default function Card({
    children,
    title,
    description,
    className = "",
    headerAction,
}: CardProps) {
    return (
        <div className={`apple-card p-6 ${className}`}>
            {(title || description || headerAction) && (
                <div className="flex items-center justify-between mb-6">
                    <div>
                        {title && (
                            <h3 className="text-lg font-semibold tracking-tight text-foreground">
                                {title}
                            </h3>
                        )}
                        {description && (
                            <p className="text-sm text-muted-foreground">
                                {description}
                            </p>
                        )}
                    </div>
                    {headerAction && <div>{headerAction}</div>}
                </div>
            )}
            <div>{children}</div>
        </div>
    )
}
