// src/app/shared/components/ui/select/select.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-select',
  imports: [CommonModule],
  templateUrl: './select.component.html',
  styleUrl: './select.component.css',
})
export class SelectComponent {
  @Input() options: { label: string; value: string }[] = [];
  @Input() value: string = '';
  @Input() label?: string;
  @Input() className: string = '';
  @Output() valueChange = new EventEmitter<string>();

  onChange(e: Event) {
    const target = e.target as HTMLSelectElement;
    this.valueChange.emit(target.value);
  }
}

<div [ngClass]="'flex flex-col gap-1.5 ' + className">
  <label *ngIf="label" class="text-sm font-medium text-muted-foreground px-1">{{ label }}</label>
  <div class="relative group">
    <select
      [value]="value"
      (change)="onChange($event)"
      class="w-full h-10 px-4 py-2 bg-secondary border border-border rounded-xl text-sm font-medium text-foreground appearance-none focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all duration-200 cursor-pointer"
    >
      <option *ngFor="let option of options" [value]="option.value">{{ option.label }}</option>
    </select>
    <div class="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-muted-foreground group-hover:text-foreground transition-colors duration-200">
      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
      </svg>
    </div>
  </div>
</div>

// src/components/ui/select.tsx
type SelectProps = {
    options: { label: string; value: string }[]
    value: string
    onChange: (value: string) => void
    label?: string
    className?: string
}

export default function Select({
    options,
    value,
    onChange,
    label,
    className = "",
}: SelectProps) {
    return (
        <div className={`flex flex-col gap-1.5 ${className}`}>
            {label && (
                <label className="text-sm font-medium text-muted-foreground px-1">
                    {label}
                </label>
            )}
            <div className="relative group">
                <select
                    value={value}
                    onChange={(e) => onChange(e.target.value)}
                    className="w-full h-10 px-4 py-2 bg-secondary border border-border rounded-xl text-sm font-medium text-foreground appearance-none focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all duration-200 cursor-pointer"
                >
                    {options.map((option) => (
                        <option key={option.value} value={option.value}>
                            {option.label}
                        </option>
                    ))}
                </select>
                <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-muted-foreground group-hover:text-foreground transition-colors duration-200">
                    <svg
                        className="w-4 h-4"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                    >
                        <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={2}
                            d="M19 9l-7 7-7-7"
                        />
                    </svg>
                </div>
            </div>
        </div>
    )
}
